name: Contracts

on:
  push:
    branches: [main]
  pull_request:

jobs:
  forge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: forge build
        working-directory: contracts
        run: forge build -vvv
